sys_arch.c:104:3: error: C++ style comments are incompatible with C90 [-Werror]
[build] ../../contrib/ports/win32/sys_arch.c:104:3: error: C++ style comments are incompatible with C90 [-Werror]
[build]   104 |   // maybe CryptAcquireContext has not been called...
[build]       |   ^
[build] ../../contrib/ports/win32/sys_arch.c:104:3: note: (this will be reported only once per input file)
[build] cc1.exe: all warnings being treated as errors