Expanding macro to string by lwip_macro_str
and output the error log of
MEMP_NUM_SYS_TIMEOUT < LWIP_NUM_SYS_TIMEOUT_INTERNAL
properly such as

```
[build]   130 | #pragma message("The value of MEMP_NUM_SYS_TIMEOUT are: " lwip_macro_str(MEMP_NUM_SYS_TIMEOUT))
[build]       |         ^~~~~~~
[build] ../../src/core/init.c:131:9: note: '#pragma message: The value of LWIP_NUM_SYS_TIMEOUT_INTERNAL are: (1 + 1 + 1 + (2*1) + 1 + 1 + 1 + (1 * (2 + (1) + (1) + 0) * (1 + 1 + 0)) + (1 * (1 + 1 + 1 + 0)))'
[build]   131 | #pragma message("The value of LWIP_NUM_SYS_TIMEOUT_INTERNAL are: " lwip_macro_str(LWIP_NUM_SYS_TIMEOUT_INTERNAL))
[build]       |         ^~~~~~~
[build] ../../src/core/init.c:132:2: error: #error "MEMP_NUM_SYS_TIMEOUT is less than LWIP_NUM_SYS_TIMEOUT_INTERNAL to accommodate all required timeouts"
[build]   132 | #error "MEMP_NUM_SYS_TIMEOUT is less than LWIP_NUM_SYS_TIMEOUT_INTERNAL to accommodate all required timeouts"
[build]       |  ^~~~~
```